export const SUBSCRIPTION_LIMITS = {
  free: {
    chatsPerDay: 20,
    doubtsPerDay: 3,
    examsPerMonth: 3,
    validationsPerMonth: 1,
    writesPerMonth: 3,
    flashcardSets: 1,
    flashcardsPerSet: 20,
    plannerDays: 7,
    availableModes: ['simple-bhai', 'class'],
    languages: ['en', 'hinglish'],
    weakAreaLimit: 3,
    parentDashboard: false,
    hasAds: true,
  },
  student: {
    chatsPerDay: 60,
    doubtsPerDay: 15,
    examsPerMonth: 20,
    validationsPerMonth: 3,
    writesPerMonth: 15,
    flashcardSets: -1, // unlimited
    flashcardsPerSet: -1,
    plannerDays: -1, // full planner
    availableModes: ['simple-bhai', 'class', 'expert', 'business', 'revision'],
    languages: ['en', 'hi', 'hinglish'],
    weakAreaLimit: -1, // full analytics
    parentDashboard: true,
    hasAds: false,
    hasDailyBriefing: true,
    hasPYQ: false,
  },
  competitive: {
    chatsPerDay: 120,
    doubtsPerDay: -1, // unlimited
    examsPerMonth: -1, // unlimited
    validationsPerMonth: 5,
    writesPerMonth: -1,
    flashcardSets: -1,
    flashcardsPerSet: -1,
    plannerDays: -1,
    availableModes: ['simple-bhai', 'class', 'expert', 'business', 'revision'],
    languages: ['en', 'hi', 'hinglish'],
    weakAreaLimit: -1,
    parentDashboard: true,
    hasAds: false,
    hasDailyBriefing: true,
    hasPYQ: true,
    hasPYQYears: 10,
    hasStudyBuddy: true,
    hasSmartNotes: true,
    hasPrioritySupport: true,
    supportResponseTime: '24hr',
  },
  pro: {
    chatsPerDay: 200,
    doubtsPerDay: -1,
    examsPerMonth: -1,
    validationsPerMonth: -1,
    writesPerMonth: -1,
    flashcardSets: -1,
    flashcardsPerSet: -1,
    plannerDays: -1,
    availableModes: ['simple-bhai', 'class', 'expert', 'business', 'revision'],
    languages: ['en', 'hi', 'hinglish'],
    weakAreaLimit: -1,
    parentDashboard: true,
    hasAds: false,
    hasDailyBriefing: true,
    hasPYQ: true,
    hasPYQYears: 10,
    hasStudyBuddy: true,
    hasSmartNotes: true,
    hasPrioritySupport: true,
    supportResponseTime: '12hr',
    hasBusinessFeatures: true,
    hasPDFExport: true,
    hasEarlyAccess: true,
  },
}

export const PLANS = {
  free: {
    name: 'Free',
    emoji: '🆓',
    price: 0,
    priceYearly: 0,
    description: 'Try karo, trust karo',
    tagline: 'Perfect for getting started',
  },
  student: {
    name: 'Student',
    emoji: '🎓',
    price: 79,
    priceYearly: 699,
    yearlySavings: 26,
    description: 'Topper banne ka sabse sasta raasta',
    tagline: 'Best for: Class 9-12 students, board exam prep',
    highlighted: true,
  },
  competitive: {
    name: 'Competitive',
    emoji: '🚀',
    price: 149,
    priceYearly: 1299,
    yearlySavings: 27,
    description: 'JEE/NEET/UPSC ke liye designed',
    tagline: 'Best for: JEE/NEET/UPSC aspirants who need deep preparation',
    highlighted: false,
  },
  pro: {
    name: 'Pro Builder',
    emoji: '💼',
    price: 199,
    priceYearly: 1799,
    yearlySavings: 25,
    description: 'Students + Entrepreneurs — best of both worlds',
    tagline: 'Best for: College students with startup dreams, young entrepreneurs, freelancers',
    highlighted: false,
  },
}

export const SPECIAL_OFFERS = [
  {
    name: 'Family Pack',
    emoji: '📦',
    description: '₹249/month for 2 siblings (both get Student Plan — saves ₹79/month)',
  },
  {
    name: 'School/Coaching Plan',
    emoji: '🏫',
    description: '₹999/month for 20 students (₹50/student — best value for coaching centers)',
  },
  {
    name: 'Referral Bonus',
    emoji: '🎁',
    description: 'Refer 3 friends who subscribe → Get 1 month free',
  },
  {
    name: 'Free Trial',
    emoji: '📱',
    description: 'First 7 Days Free on any paid plan — no credit card required',
  },
]
