// Indian Exam Patterns Configuration

export interface ExamPattern {
  id: string
  name: string
  icon: string
  description: string
  subjects: string[]
  totalQuestions: number
  duration: number // in minutes
  markingScheme: {
    correct: number
    incorrect: number
  }
  hasSections: boolean
  sections?: {
    name: string
    subject: string
    questions: number
  }[]
  color: string
}

export const EXAM_PATTERNS: Record<string, ExamPattern> = {
  JEE_MAINS: {
    id: 'jee-mains',
    name: 'JEE Main',
    icon: '🎯',
    description: 'NTA pattern with Physics, Chemistry, Mathematics',
    subjects: ['Physics', 'Chemistry', 'Mathematics'],
    totalQuestions: 75,
    duration: 180, // 3 hours
    markingScheme: {
      correct: 4,
      incorrect: -1,
    },
    hasSections: true,
    sections: [
      { name: 'Physics', subject: 'Physics', questions: 25 },
      { name: 'Chemistry', subject: 'Chemistry', questions: 25 },
      { name: 'Mathematics', subject: 'Mathematics', questions: 25 },
    ],
    color: '#534AB7',
  },
  NEET: {
    id: 'neet',
    name: 'NEET UG',
    icon: '🩺',
    description: 'Medical entrance with Biology focus',
    subjects: ['Physics', 'Chemistry', 'Biology'],
    totalQuestions: 180,
    duration: 200, // 3 hours 20 minutes
    markingScheme: {
      correct: 4,
      incorrect: -1,
    },
    hasSections: true,
    sections: [
      { name: 'Physics', subject: 'Physics', questions: 45 },
      { name: 'Chemistry', subject: 'Chemistry', questions: 45 },
      { name: 'Botany', subject: 'Biology', questions: 45 },
      { name: 'Zoology', subject: 'Biology', questions: 45 },
    ],
    color: '#1D9E75',
  },
  CBSE_BOARD: {
    id: 'cbse-board',
    name: 'CBSE Board',
    icon: '📚',
    description: 'Class 12 Board Exam pattern',
    subjects: ['Physics', 'Chemistry', 'Mathematics', 'Biology', 'English'],
    totalQuestions: 30,
    duration: 180,
    markingScheme: {
      correct: 1,
      incorrect: 0, // No negative marking in boards
    },
    hasSections: false,
    color: '#BA7517',
  },
  UPSC_PRELIMS: {
    id: 'upsc-prelims',
    name: 'UPSC Prelims',
    icon: '🏛️',
    description: 'Civil Services Preliminary Exam',
    subjects: ['General Studies', 'CSAT'],
    totalQuestions: 200,
    duration: 120, // 2 hours per paper
    markingScheme: {
      correct: 2,
      incorrect: -0.66,
    },
    hasSections: true,
    sections: [
      { name: 'General Studies', subject: 'General Studies', questions: 100 },
      { name: 'CSAT', subject: 'CSAT', questions: 80 },
    ],
    color: '#3C3489',
  },
  SSC_CGL: {
    id: 'ssc-cgl',
    name: 'SSC CGL',
    icon: '📊',
    description: 'Staff Selection Commission Exam',
    subjects: ['General Intelligence', 'Quantitative Aptitude', 'English', 'General Awareness'],
    totalQuestions: 100,
    duration: 60,
    markingScheme: {
      correct: 2,
      incorrect: -0.5,
    },
    hasSections: false,
    color: '#E74C3C',
  },
  CUSTOM: {
    id: 'custom',
    name: 'Custom Test',
    icon: '⚙️',
    description: 'Create your own test',
    subjects: [],
    totalQuestions: 0,
    duration: 0,
    markingScheme: {
      correct: 1,
      incorrect: 0,
    },
    hasSections: false,
    color: '#6B6B80',
  },
}

export const SUBJECT_TOPICS: Record<string, string[]> = {
  Physics: [
    'Mechanics',
    'Thermodynamics',
    'Electromagnetism',
    'Optics',
    'Modern Physics',
    'Waves and Oscillations',
    'Kinematics',
    'Laws of Motion',
    'Work, Energy and Power',
    'Rotational Motion',
    'Gravitation',
    'Properties of Matter',
    'Electrostatics',
    'Current Electricity',
    'Magnetic Effects of Current',
    'Electromagnetic Induction',
    'Alternating Current',
    'Electromagnetic Waves',
    'Ray Optics',
    'Wave Optics',
    'Dual Nature of Matter',
    'Atoms and Nuclei',
    'Semiconductor Electronics',
  ],
  Chemistry: [
    'Atomic Structure',
    'Chemical Bonding',
    'States of Matter',
    'Thermodynamics',
    'Equilibrium',
    'Redox Reactions',
    'Organic Chemistry - Basic Principles',
    'Hydrocarbons',
    'Environmental Chemistry',
    'Solutions',
    'Electrochemistry',
    'Chemical Kinetics',
    'Surface Chemistry',
    'p-Block Elements',
    'd- and f-Block Elements',
    'Coordination Compounds',
    'Haloalkanes and Haloarenes',
    'Alcohols, Phenols and Ethers',
    'Aldehydes, Ketones and Carboxylic Acids',
    'Amines',
    'Biomolecules',
    'Polymers',
    'Chemistry in Everyday Life',
  ],
  Mathematics: [
    'Sets and Functions',
    'Trigonometry',
    'Algebra',
    'Coordinate Geometry',
    'Calculus',
    'Mathematical Reasoning',
    'Statistics and Probability',
    'Relations and Functions',
    'Inverse Trigonometric Functions',
    'Matrices and Determinants',
    'Continuity and Differentiability',
    'Application of Derivatives',
    'Integrals',
    'Application of Integrals',
    'Differential Equations',
    'Vector Algebra',
    'Three Dimensional Geometry',
    'Linear Programming',
    'Probability',
    'Complex Numbers',
    'Quadratic Equations',
    'Sequences and Series',
    'Straight Lines',
    'Conic Sections',
    'Limits and Derivatives',
    'Permutations and Combinations',
    'Binomial Theorem',
  ],
  Biology: [
    'Diversity in Living World',
    'Structural Organisation',
    'Cell Structure and Function',
    'Plant Physiology',
    'Human Physiology',
    'Reproduction',
    'Genetics and Evolution',
    'Biology and Human Welfare',
    'Biotechnology',
    'Ecology and Environment',
    'Morphology of Flowering Plants',
    'Anatomy of Flowering Plants',
    'Cell Cycle and Cell Division',
    'Transport in Plants',
    'Mineral Nutrition',
    'Photosynthesis',
    'Respiration in Plants',
    'Plant Growth and Development',
    'Digestion and Absorption',
    'Breathing and Exchange of Gases',
    'Body Fluids and Circulation',
    'Excretory Products and Elimination',
    'Locomotion and Movement',
    'Neural Control and Coordination',
    'Chemical Coordination and Integration',
    'Sexual Reproduction in Flowering Plants',
    'Human Reproduction',
    'Reproductive Health',
    'Principles of Inheritance and Variation',
    'Molecular Basis of Inheritance',
    'Evolution',
    'Human Health and Disease',
    'Strategies for Enhancement in Food Production',
    'Microbes in Human Welfare',
    'Organisms and Populations',
    'Ecosystem',
    'Biodiversity and Conservation',
    'Environmental Issues',
  ],
  English: [
    'Reading Comprehension',
    'Grammar',
    'Writing Skills',
    'Literature',
    'Vocabulary',
    'Sentence Correction',
    'Fill in the Blanks',
    'Synonyms and Antonyms',
    'Idioms and Phrases',
    'One Word Substitution',
  ],
  'General Studies': [
    'History',
    'Geography',
    'Polity',
    'Economics',
    'Science and Technology',
    'Environment and Ecology',
    'Current Affairs',
    'Indian National Movement',
    'Physical Geography',
    'Indian Polity',
    'Indian Economy',
    'General Science',
  ],
  CSAT: [
    'Comprehension',
    'Interpersonal Skills',
    'Logical Reasoning',
    'Analytical Ability',
    'Decision Making',
    'Basic Numeracy',
    'Data Interpretation',
  ],
  'General Intelligence': [
    'Analogy',
    'Classification',
    'Series',
    'Coding-Decoding',
    'Blood Relations',
    'Direction and Distance',
    'Syllogism',
    'Venn Diagrams',
    'Puzzles',
    'Non-Verbal Reasoning',
  ],
  'Quantitative Aptitude': [
    'Number System',
    'Percentage',
    'Profit and Loss',
    'Simple and Compound Interest',
    'Ratio and Proportion',
    'Average',
    'Time and Work',
    'Time, Speed and Distance',
    'Algebra',
    'Geometry',
    'Mensuration',
    'Trigonometry',
    'Data Interpretation',
  ],
  'General Awareness': [
    'Current Affairs',
    'Indian History',
    'Geography',
    'Indian Polity',
    'Economics',
    'Science',
    'Sports',
    'Awards and Honors',
    'Books and Authors',
  ],
}

export const DIFFICULTY_LEVELS = ['Easy', 'Medium', 'Hard'] as const
export type DifficultyLevel = typeof DIFFICULTY_LEVELS[number]
